// flow-typed signature: edfbecc9edaadab1a3f527b34d2dc077
// flow-typed version: <<STUB>>/fixed-size-queue_v^1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fixed-size-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fixed-size-queue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fixed-size-queue/spec/QueueSpec' {
  declare module.exports: any;
}

declare module 'fixed-size-queue/src/Queue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fixed-size-queue/index' {
  declare module.exports: $Exports<'fixed-size-queue'>;
}
declare module 'fixed-size-queue/index.js' {
  declare module.exports: $Exports<'fixed-size-queue'>;
}
declare module 'fixed-size-queue/spec/QueueSpec.js' {
  declare module.exports: $Exports<'fixed-size-queue/spec/QueueSpec'>;
}
declare module 'fixed-size-queue/src/Queue.js' {
  declare module.exports: $Exports<'fixed-size-queue/src/Queue'>;
}
