// flow-typed signature: 879ea729fcae3cb75a5b92112832c308
// flow-typed version: <<STUB>>/react-native-interactable_v^0.0.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-interactable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-interactable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-interactable/real-life-example/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/app' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/ChatHeads' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/CollapsibleCalendar' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/CollapsibleFilter' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/Documentation' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/MapPanel' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/NotifPanel' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/NowCard' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/RowActions1' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/RowActions2' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/TinderCard' {
  declare module.exports: any;
}

declare module 'react-native-interactable/real-life-example/src/UxInspirations' {
  declare module.exports: any;
}

declare module 'react-native-interactable/src/InteractableView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-interactable/index' {
  declare module.exports: $Exports<'react-native-interactable'>;
}
declare module 'react-native-interactable/index.js' {
  declare module.exports: $Exports<'react-native-interactable'>;
}
declare module 'react-native-interactable/real-life-example/__tests__/index.android.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/__tests__/index.android'>;
}
declare module 'react-native-interactable/real-life-example/__tests__/index.ios.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/__tests__/index.ios'>;
}
declare module 'react-native-interactable/real-life-example/index.android.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/index.android'>;
}
declare module 'react-native-interactable/real-life-example/index.ios.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/index.ios'>;
}
declare module 'react-native-interactable/real-life-example/src/app.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/app'>;
}
declare module 'react-native-interactable/real-life-example/src/ChatHeads.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/ChatHeads'>;
}
declare module 'react-native-interactable/real-life-example/src/CollapsibleCalendar.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/CollapsibleCalendar'>;
}
declare module 'react-native-interactable/real-life-example/src/CollapsibleFilter.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/CollapsibleFilter'>;
}
declare module 'react-native-interactable/real-life-example/src/Documentation.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/Documentation'>;
}
declare module 'react-native-interactable/real-life-example/src/MapPanel.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/MapPanel'>;
}
declare module 'react-native-interactable/real-life-example/src/NotifPanel.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/NotifPanel'>;
}
declare module 'react-native-interactable/real-life-example/src/NowCard.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/NowCard'>;
}
declare module 'react-native-interactable/real-life-example/src/RowActions1.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/RowActions1'>;
}
declare module 'react-native-interactable/real-life-example/src/RowActions2.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/RowActions2'>;
}
declare module 'react-native-interactable/real-life-example/src/TinderCard.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/TinderCard'>;
}
declare module 'react-native-interactable/real-life-example/src/UxInspirations.js' {
  declare module.exports: $Exports<'react-native-interactable/real-life-example/src/UxInspirations'>;
}
declare module 'react-native-interactable/src/InteractableView.js' {
  declare module.exports: $Exports<'react-native-interactable/src/InteractableView'>;
}
